// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoXDXkvlz2-STCENyQXkBbvauGl0p_4Fc',
    appId: '1:313369468080:web:054cbf9acdb6b63d8caf75',
    messagingSenderId: '313369468080',
    projectId: 'ev-home-customer',
    authDomain: 'ev-home-customer.firebaseapp.com',
    storageBucket: 'ev-home-customer.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK0WOrlwUR_SS-2fLe1lQnfzjolk5C3PQ',
    appId: '1:313369468080:android:ad73013a2abcd37c8caf75',
    messagingSenderId: '313369468080',
    projectId: 'ev-home-customer',
    storageBucket: 'ev-home-customer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF_pmt249m-M4RPkeo_OjX_Zi3ryoIRqI',
    appId: '1:313369468080:ios:c3aadc4f5afa92f28caf75',
    messagingSenderId: '313369468080',
    projectId: 'ev-home-customer',
    storageBucket: 'ev-home-customer.appspot.com',
    iosBundleId: 'com.example.evHomesCustomer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF_pmt249m-M4RPkeo_OjX_Zi3ryoIRqI',
    appId: '1:313369468080:ios:c3aadc4f5afa92f28caf75',
    messagingSenderId: '313369468080',
    projectId: 'ev-home-customer',
    storageBucket: 'ev-home-customer.appspot.com',
    iosBundleId: 'com.example.evHomesCustomer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoXDXkvlz2-STCENyQXkBbvauGl0p_4Fc',
    appId: '1:313369468080:web:40b36e4850155cac8caf75',
    messagingSenderId: '313369468080',
    projectId: 'ev-home-customer',
    authDomain: 'ev-home-customer.firebaseapp.com',
    storageBucket: 'ev-home-customer.appspot.com',
  );
}
